title: "Brandon's Tech Blog"
description: "Learning notes on Embedded System, IC Design, and more"
theme: minima
timezone: Asia/Taipei

url: "https://brandon-git-hub.github.io"
baseurl: "/TechBlog"

header_pages:
  - index.md
  - categories.md

include:
  - "**/*.bat"
  - "**/*.ps1"
  - "**/*.json"
